version: "3.7"

networks:
  multizone:

services:
  blog:
    container_name: blog
    image: blog:v3
    build:
      context: .
      dockerfile: ./blog/Dockerfile
    ports:
      - 4000:4000
    tty: true
    stdin_open: true
    networks:
      - multizone

  home:
    container_name: home
    image: home:v3
    build:
      context: .
      dockerfile: ./home/Dockerfile
      args:
        - BLOG_URL=http://blog:4000
        # - BLOG_URL=https://with-zones-blog.vercel.app
        # - BLOG_URL=http://blog:4000
    ports:
      - 4001:4001
    tty: true
    stdin_open: true
    networks:
      - multizone
